# Generated by Django 2.1.3 on 2018-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='best',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='jest',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='test',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
